version: "3"
services:
  collector:
    build: .
    volumes:
      - ./:/home/collector
      - /home/ywatanabe/PhishData:/home/collector/PhishData
      - /home/ywatanabe/public_html/tmp/:/home/collector/tmp/
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true