[tool.poetry]
name = "collector"
version = "1.5.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.112.0"
uvicorn = { extras = ["standard"], version = "0.30.5" }
playwright = "1.45.1"
playwright-stealth = "1.0.6"
setuptools = "72.1.0"
pillow = "^10.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
